[olympicpark_schedule]
title = "올림픽공원 ─ 조이올팍 공연/행사 ─ 일정안내"
url = "https://olympicpark.kspo.or.kr:441/jsp/homepage/contents/culture/schedule_dselect_action.do"
entrySelector = "tbody[id='listBody'] tr td"
titleSelector = "dl.desc dt.text_bold a"
linkSelector = "dl.desc dt.text_bold a"
contentSelector = "dd.pd_t5 span.text_blue"
imageSelector = "p.photo a img"
waitUntil = "networkidle"

[olympicpark_kspodome]
title = "올림픽공원 ─ 조이올팍 공연/행사 ─ 일정안내"
url = "https://olympicpark.kspo.or.kr:441/jsp/homepage/contents/culture/schedule_dselect_action.do#sort2"
entrySelector = "tbody[id='listBody'] tr td"
titleSelector = "dl.desc dt.text_bold a"
linkSelector = "dl.desc dt.text_bold a"
contentSelector = "dd.pd_t5 span.text_blue"
imageSelector = "p.photo a img"
waitUntil = "networkidle"

[olympicpark_schedule_venue]
title = "올림픽공원 ─ 조이올팍 공연/행사 ─ 일정안내 (장소별)"
url = "https://olympicpark.kspo.or.kr:441/jsp/homepage/contents/culture/schedule_pselect_action.do"
entrySelector = "ul li.pd_b40:nth-child(1) div table tbody tr td"
titleSelector = "dt.text_bold a"
linkSelector = "dt.text_bold a"
contentSelector = "dd.pd_t5 span.text_blue"
imageSelector = "p.photo a img"
waitUntil = "networkidle"